// Initial data - 31 reglamentos reales del nuevo estatuto UMAG
// Observaciones: datos Excel + interconexiones entre reglamentos
export const INITIAL_REGULATIONS = [
  { id: 1, numero: "1", nombre: "Reglamento de Funcionamiento del Consejo Superior", articulo: "Título IV, Art. 11-15", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "⚡ DEPENDENCIA: Es prerrequisito para #4 (Nombramiento CS) ya aprobado. Habilita la gobernanza institucional junto con #5 (CU) y #6 (Elecciones).", enlace: "", decreto: "", articulo_estatuto: "Art. 11-15", historial: [], adjuntos: [] },
  { id: 2, numero: "2", nombre: "Declaración de Bienes de Especial Interés Institucional", articulo: "", estado: "En Revisión", progreso: 40, prioridad: "media", responsable: "VRAF", observaciones: "Se remitió a VRAF para observaciones. 🔗 CONEXIÓN: Se vincula con #22 (Administración Financiera, Art. 86) en materia patrimonial. Conviene coordinar definiciones con VRAF para coherencia normativa.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 3, numero: "3", nombre: "Reglamento de Elección del Rector o Rectora", articulo: "", estado: "En Revisión", progreso: 35, prioridad: "alta", responsable: "Secretaría General", observaciones: "Revisar el actual reglamento. ✅ PRERREQUISITO CUMPLIDO: #6 (Reglamento General de Elecciones) ya aprobado — establece marco electoral general. 🔗 CONEXIÓN: Art. 16-19 del Estatuto. Debe ser coherente con procedimientos definidos en #6.", enlace: "https://drive.google.com/file/d/1_aUgV1I19T2AwTcB12pfBxtWbvrZ5SJr/view?usp=sharing", decreto: "DEC EX. 20/2022", articulo_estatuto: "Art. 16-19", historial: [], adjuntos: [] },
  { id: 4, numero: "4", nombre: "Reglamento para Nombramiento de Miembros de la Comunidad Universitaria en el Consejo Superior", articulo: "Art. 12-13", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "✅ PRERREQUISITOS CUMPLIDOS: #1 (Funcionamiento CS) y #6 (Elecciones) aprobados. 🔗 CONEXIÓN: Complementa a #1 definiendo la integración del CS.", enlace: "https://gestor.umag.cl/storage/2025/326/versiones/13/firmas/DEC-N2SU2025PDF-firmado-1.pdf", decreto: "DEC N°2/SU/2025", articulo_estatuto: "Art. 12-13", historial: [], adjuntos: [] },
  { id: 5, numero: "5", nombre: "Reglamento de Funcionamiento Interno del Consejo Universitario", articulo: "Art. 23-28", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "⚡ DEPENDENCIA: Es el órgano que aprueba los demás reglamentos. Su aprobación habilita el trámite formal de todos los reglamentos pendientes.", enlace: "https://gestor.umag.cl/storage/2025/324/versiones/4/firmas/DEC-N001SU2025PDF-firmado-1.pdf", decreto: "DEC N°001/SU/2025", articulo_estatuto: "Art. 23-28", historial: [], adjuntos: [] },
  { id: 6, numero: "6", nombre: "Reglamento General de Elecciones", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "[05/09/2025] Propuestas de Mejora: Incorporar al art. 20 alternativas cuando no se presenten candidatos. Eliminar art. 47 sobre consejeros de centro. ⚡ DEPENDENCIA: Es prerrequisito para #3 (Elección Rector). Establece marco electoral general aplicable a #4 (Nombramiento CS) y #31 (Votaciones Bienestar).", enlace: "https://gestor.umag.cl/verificar/IenybNt1", decreto: "DEC N°007/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 7, numero: "7", nombre: "Reglamento de Secretaría General", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "Se debe presentar al CU del 28/08/2025. ⚡ DEPENDENCIA: Define funciones de SG como ministro de fe y tramitador de normas. Relevante para #27 (Emisión de Normas) y #28 (Convenios).", enlace: "https://gestor.umag.cl/storage/2025/2347/versiones/4/firmas/DEC-N28SU2025PDF-firmado-1.pdf", decreto: "DEC N°28/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 8, numero: "8", nombre: "Reglamento General de Facultades", articulo: "", estado: "En Revisión", progreso: 30, prioridad: "media", responsable: "VRAC", observaciones: "Revisar si se puede fusionar con el reglamento de estructuras. 🔗 CONEXIÓN: Posible fusión con #11 (Estructuras Académicas) — ambos regulan organización académica. Deben coordinarse antes de avanzar por separado. ⚡ DEPENDENCIA: Su definición impacta #10 (Estudios) y #13 (Carrera Académica) al establecer la estructura donde operan.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 9, numero: "9", nombre: "Reglamento de Gestión, Evaluación y Aseguramiento de la Calidad", articulo: "Art. 53 letra a y b", estado: "En Revisión", progreso: 35, prioridad: "alta", responsable: "Dir. Aseguramiento de la Calidad", observaciones: "Art. 53 Estatutos letra a y b. 🔗 CONEXIÓN: Interdependiente con #12 (Comité de Aseguramiento de la Calidad) — #9 define el sistema, #12 define el órgano que lo implementa. Deben redactarse en paralelo. ⚡ DEPENDENCIA: Impacta #10 (Estudios) en materia de estándares de calidad académica.", enlace: "", decreto: "", articulo_estatuto: "Art. 53", historial: [], adjuntos: [] },
  { id: 10, numero: "10", nombre: "Reglamento de Estudios", articulo: "Art. 55", estado: "Pendiente", progreso: 10, prioridad: "alta", responsable: "VRAC", observaciones: "Art. 55 del estatuto. Revisar con Mario. 🔗 CONEXIÓN: Requiere definiciones previas de #8/#11 (estructura de facultades) y #9 (estándares de calidad). Se vincula con #18 (General Estudiantes) en materia de derechos y deberes académicos, y con #29 (Compatibilidad Estudios) en flexibilidad curricular. ⚡ PRERREQUISITOS: Avanzar #8/#11 y #9 primero.", enlace: "", decreto: "", articulo_estatuto: "Art. 55", historial: [], adjuntos: [] },
  { id: 11, numero: "11", nombre: "Reglamento de Estructuras Académicas", articulo: "", estado: "En Revisión", progreso: 35, prioridad: "media", responsable: "VRAC / Dir. Docencia", observaciones: "Se presentó propuesta a VRAC, VRAF, SG y D. de Docencia. [27/08/2025] La dirección de docencia coordinará reunión con decanos para revisión. 🔗 CONEXIÓN: Posible fusión con #8 (General de Facultades). Decisión de fusionar o no es BLOQUEANTE para ambos. ⚡ DEPENDENCIA: Define la estructura donde operan #13 (Carrera), #15 (Jerarquía) y #10 (Estudios).", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 12, numero: "12", nombre: "Reglamento del Comité de Aseguramiento de la Calidad", articulo: "", estado: "En Revisión", progreso: 30, prioridad: "media", responsable: "Dir. Aseguramiento de la Calidad", observaciones: "Fue remitido con observaciones a la Dirección de Aseguramiento de la Calidad. 🔗 CONEXIÓN: Interdependiente con #9 (Gestión de Calidad) — #12 crea el comité que ejecuta lo que #9 norma. Deben aprobarse de forma coordinada.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 13, numero: "13", nombre: "Reglamento de Carrera Académica", articulo: "Art. 67", estado: "En Revisión", progreso: 25, prioridad: "alta", responsable: "Dir. Docencia", observaciones: "Art. 67. [27/08/2025] @Pablo André Galaz Saavedra: recopilar reglamentos de otras universidades y generar listado de materias a regular. Se encuentra regulado en el art. 67 del Estatuto, probablemente debamos fusionarlo con el de jerarquía e inclusive con el de carga. Se habló con Mario y se acordó reunión con gestión docente. 🔗 CONEXIÓN: Posible fusión con #15 (Jerarquía) y relación directa con #14 (Carga, ya aprobado). ⚡ DEPENDENCIA: Es prerrequisito para #16 (Promoción, Art. 68) — no se puede definir promoción sin definir carrera. Requiere que #8/#11 (estructura) esté definida.", enlace: "", decreto: "", articulo_estatuto: "Art. 67", historial: [], adjuntos: [] },
  { id: 14, numero: "14", nombre: "Reglamento de Asignación de Carga Académica", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Dir. Docencia", observaciones: "[05/09/2025] Propuestas de Mejora: Se debe considerar en la carga administrativa a los coordinadores de campus. 🔗 CONEXIÓN: Se relaciona con #13 (Carrera Académica) y #15 (Jerarquía) en la definición de funciones docentes. Ya aprobado — sirve como insumo para la redacción de #13.", enlace: "https://gestor.umag.cl/verificar/hBeJOFkT", decreto: "DEC N°15/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 15, numero: "15", nombre: "Reglamento de Jerarquía Académica", articulo: "", estado: "En Revisión", progreso: 25, prioridad: "media", responsable: "Dir. Docencia", observaciones: "[27/08/2025] Dirección de Docencia propuso generar reunión entre DJ, DD y la Unidad de Gestión docente. 🔗 CONEXIÓN: Posible fusión con #13 (Carrera Académica). Define categorías que usa #16 (Promoción) y #14 (Carga, ya aprobado). ⚡ DEPENDENCIA: Debe coordinarse con #13 antes de avanzar — decisión de fusión es BLOQUEANTE.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 16, numero: "16", nombre: "Reglamento de Promoción de un Académico", articulo: "Art. 68", estado: "En Proceso", progreso: 15, prioridad: "media", responsable: "Dir. Docencia", observaciones: "Art. 68. En redacción. 🔗 CONEXIÓN: Depende directamente de #13 (Carrera Académica, Art. 67) y #15 (Jerarquía). No se puede aprobar promoción sin tener definida carrera y jerarquía. ⚡ PRERREQUISITOS: #13 y #15 deben estar al menos en revisión avanzada antes de finalizar este reglamento.", enlace: "", decreto: "", articulo_estatuto: "Art. 68", historial: [], adjuntos: [] },
  { id: 17, numero: "17", nombre: "Reglamento de Estímulos e Incentivos a Funcionarios de Apoyo", articulo: "Art. 71", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "VRAF", observaciones: "Art. 71. En estudio. 🔗 CONEXIÓN: Se vincula con #22 (Administración Financiera, Art. 86) para el marco presupuestario de incentivos. Independiente del bloque académico.", enlace: "", decreto: "", articulo_estatuto: "Art. 71", historial: [], adjuntos: [] },
  { id: 18, numero: "18", nombre: "Reglamento General de Estudiantes", articulo: "", estado: "En Proceso", progreso: 45, prioridad: "alta", responsable: "VRAE", observaciones: "Propuesta presentada al Consejo Universitario. ⚡ DEPENDENCIA: Es la norma base estudiantil. Su aprobación es prerrequisito para #21 (Convivencia, Art. 81) y #29 (Compatibilidad Estudios, Ley 21.790). Se complementa con #20 (Disciplinarios, ya aprobado) y #10 (Estudios).", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 19, numero: "19", nombre: "Reglamento para Uso de Bienes y Servicios de la Universidad", articulo: "Art. 78 letra f)", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "VRAF", observaciones: "Art. 78 letra f). En estudio. 🔗 CONEXIÓN: Norma específica derivada de #22 (Administración Financiera, Art. 86). Conviene definir primero el marco general (#22) antes de regular el uso específico.", enlace: "", decreto: "", articulo_estatuto: "Art. 78", historial: [], adjuntos: [] },
  { id: 20, numero: "20", nombre: "Reglamento de Procedimientos Disciplinarios de Estudiantes", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "El día 27 de agosto de 2025 se responden observaciones del Sr. Contralor. [22/10/2025] Observaciones de Dayana: https://docs.google.com/document/d/1D4iroX87I0FdohIUV-w7xOy5NF8cgWVr/edit. 🔗 CONEXIÓN: Se complementa con #18 (General Estudiantes) y #21 (Convivencia). Establece procedimientos que #21 puede invocar para sanciones.", enlace: "https://gestor.umag.cl/storage/2025/538/versiones/3/firmas/DEC-N21SU2025PDF-firmado-1.pdf", decreto: "DEC N°21/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 21, numero: "21", nombre: "Reglamento del Consejo de Convivencia Universitaria", articulo: "Art. 81", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "Secretaría General", observaciones: "Art. 81. En estudio. 🔗 CONEXIÓN: Se vincula con #20 (Disciplinarios, ya aprobado) para derivación de casos y con #26 (Mediador Universitario) como instancia previa. ⚡ PRERREQUISITOS: Requiere #18 (General Estudiantes) para definir sujetos y derechos. Conviene avanzar #26 (Mediador) en paralelo.", enlace: "", decreto: "", articulo_estatuto: "Art. 81", historial: [], adjuntos: [] },
  { id: 22, numero: "22", nombre: "Reglamento sobre Administración Financiera y Patrimonial", articulo: "Art. 86 letra g)", estado: "Pendiente", progreso: 5, prioridad: "alta", responsable: "VRAF", observaciones: "Art. 86 letra g). En estudio. ⚡ DEPENDENCIA: Es el marco financiero general. Su aprobación es prerrequisito para #19 (Uso de Bienes, Art. 78) y #28 (Convenios). Se vincula con #2 (Bienes de Interés) y #17 (Estímulos) en materia presupuestaria.", enlace: "", decreto: "", articulo_estatuto: "Art. 86", historial: [], adjuntos: [] },
  { id: 23, numero: "23", nombre: "Reglamento sobre Propiedad Intelectual", articulo: "Art. 90", estado: "Pendiente", progreso: 15, prioridad: "media", responsable: "VRI / Pedro Herrera", observaciones: "Art. 90. [29/08/2025] Se le solicita a Pedro Herrera revisar el reglamento en función a los nuevos estatutos. [05/09/2025] Ajuste normativo lo realizará Pedro Herrera, presentación para CU de octubre 2025. 🔗 CONEXIÓN: Se relaciona con #24 (Protección de Datos) en materia de resguardo de información y activos intangibles. Independiente del resto, puede avanzar en paralelo.", enlace: "https://drive.google.com/file/d/1C32f_54Amsw6CY9YGTIm3yYnvKftIEKy/view?usp=sharing", decreto: "DEC N°004/SU/2023", articulo_estatuto: "Art. 90", historial: [], adjuntos: [] },
  { id: 24, numero: "24", nombre: "Protocolo de Protección de Datos", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "Secretaría General", observaciones: "En estudio. 🔗 CONEXIÓN: Se vincula con #23 (Propiedad Intelectual) en protección de activos intangibles. Transversal a toda la institución. Puede avanzar en paralelo con los demás bloques.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 25, numero: "25", nombre: "Reglamento de Orden, Higiene y Seguridad", articulo: "", estado: "En Revisión", progreso: 30, prioridad: "media", responsable: "VRAF", observaciones: "🔗 CONEXIÓN: Regulación laboral transversal. Se vincula con #17 (Estímulos e Incentivos) en condiciones laborales. Sin dependencias bloqueantes, puede avanzar en paralelo.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 26, numero: "26", nombre: "Normativa del Mediador Universitario", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "baja", responsable: "Secretaría General", observaciones: "En estudio. 🔗 CONEXIÓN: Instancia previa a #21 (Convivencia) y complementaria a #20 (Disciplinarios, ya aprobado). Conviene avanzar en paralelo con #21 para coherencia en resolución de conflictos.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 27, numero: "27", nombre: "Normativa Relativa para la Emisión de Normas", articulo: "", estado: "Pendiente", progreso: 10, prioridad: "media", responsable: "Secretaría General", observaciones: "[09/09/2025] Se debe crear una normativa que regule en qué caso debe emitirse una política, reglamento, instructivo, circular. Además podría incluirse materias relativas a decretos y resoluciones. Pasos: Buscar normativa similar, establecer instrumentos, determinar elementos mínimos. ⚡ DEPENDENCIA CRÍTICA: Esta normativa define el marco formal para TODOS los demás reglamentos pendientes. Su aprobación temprana otorga coherencia y legitimidad al resto del proceso normativo. Se vincula con #7 (SG, ya aprobado) que ejecuta la tramitación. RECOMENDACIÓN: Priorizar como primer hito.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 28, numero: "28", nombre: "Reglamento de Tramitación de Convenios y Contratos", articulo: "", estado: "Pendiente", progreso: 10, prioridad: "media", responsable: "Secretaría General", observaciones: "[09/09/2025] Pasos: Crear Drive con material. Reunir normativa similar. Recabar opinión de Contraloría. Reunión equipo jurídico. Redacción de documento. 🔗 CONEXIÓN: Requiere definiciones de #22 (Administración Financiera) para marco presupuestario de convenios. Se vincula con #7 (SG, ya aprobado) para tramitación formal. ⚡ PRERREQUISITO: #22 debería avanzar primero.", enlace: "", decreto: "Res. N°216/2019", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 29, numero: "29", nombre: "Normativa de Compatibilidad Estudios con Vida Familiar", articulo: "", estado: "Pendiente", progreso: 10, prioridad: "alta", responsable: "VRAE", observaciones: "[09/02/2026] Se debe redactar normativa de acuerdo al tenor de la Ley 21.790 sobre derechos de estudiantes cuidadores. 🔗 CONEXIÓN: Se vincula con #18 (General Estudiantes) como norma base de derechos estudiantiles y con #10 (Estudios) para flexibilidad curricular. ⚡ PRERREQUISITO EXTERNO: Ley 21.790 obliga a la universidad — tiene urgencia legal. Conviene avanzar en paralelo con #18.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 30, numero: "30", nombre: "Reglamento de Incentivo al Retiro", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "baja", responsable: "VRAF", observaciones: "En estudio. 🔗 CONEXIÓN: Se vincula con #22 (Administración Financiera) para disponibilidad presupuestaria y con #17 (Estímulos) en política de RRHH. Sin dependencias bloqueantes directas.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 31, numero: "31", nombre: "Reglamento de Votaciones Bienestar", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "baja", responsable: "VRAE / Bienestar", observaciones: "En estudio. 🔗 CONEXIÓN: Debe ser coherente con #6 (Elecciones, ya aprobado) en materia de procedimientos electorales internos. Sin dependencias bloqueantes.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] }
];

export const PLAZOS_DATA = [
  { id: 1, gestion: "Revisión de redacción", plazo: "90 días desde la propuesta", objeto: "Validar contenido normativo", formalidad: "Comisión de Redacción", requisito: "Propuesta inicial" },
  { id: 2, gestion: "Consulta a académicos", plazo: "60 días", objeto: "Incorporar feedback", formalidad: "Consulta pública", requisito: "Borrador disponible" },
  { id: 3, gestion: "Aprobación de Consejo", plazo: "45 días", objeto: "Aprobación final", formalidad: "Sesión del Consejo", requisito: "Informe favorable" },
  { id: 4, gestion: "Publicación oficial", plazo: "15 días", objeto: "Difusión general", formalidad: "Publicación web y gaceta", requisito: "Aprobación del Consejo" },
  { id: 5, gestion: "Implementación", plazo: "30 días", objeto: "Capacitación e inicio", formalidad: "Plan de implementación", requisito: "Publicación oficial" },
  { id: 6, gestion: "Seguimiento", plazo: "Permanente", objeto: "Monitoreo de cumplimiento", formalidad: "Reportes trimestrales", requisito: "Implementación activa" }
];
