// Initial data - 31 reglamentos reales del nuevo estatuto UMAG
export const INITIAL_REGULATIONS = [
  { id: 1, numero: "1", nombre: "Reglamento de Funcionamiento del Consejo Superior", articulo: "Título IV, Art. 11-15", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "", enlace: "", decreto: "", articulo_estatuto: "Art. 11-15", historial: [], adjuntos: [] },
  { id: 2, numero: "2", nombre: "Declaración de Bienes de Especial Interés Institucional", articulo: "", estado: "En Revisión", progreso: 40, prioridad: "media", responsable: "VRAF", observaciones: "Se remitió a VRAF para observaciones", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 3, numero: "3", nombre: "Reglamento de Elección del Rector o Rectora", articulo: "", estado: "En Revisión", progreso: 35, prioridad: "alta", responsable: "Secretaría General", observaciones: "Revisar el actual reglamento (Dec. Ex. 20/2022)", enlace: "https://drive.google.com/file/d/1_aUgV1I19T2AwTcB12pfBxtWbvrZ5SJr/view?usp=sharing", decreto: "DEC EX. 20/2022", articulo_estatuto: "Art. 16-19", historial: [], adjuntos: [] },
  { id: 4, numero: "4", nombre: "Reglamento para Nombramiento de Miembros de la Comunidad Universitaria en el Consejo Superior", articulo: "Art. 12-13", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "", enlace: "https://gestor.umag.cl/storage/2025/326/versiones/13/firmas/DEC-N2SU2025PDF-firmado-1.pdf", decreto: "DEC N°2/SU/2025", articulo_estatuto: "Art. 12-13", historial: [], adjuntos: [] },
  { id: 5, numero: "5", nombre: "Reglamento de Funcionamiento Interno del Consejo Universitario", articulo: "Art. 23-28", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "", enlace: "https://gestor.umag.cl/storage/2025/324/versiones/4/firmas/DEC-N001SU2025PDF-firmado-1.pdf", decreto: "DEC N°001/SU/2025", articulo_estatuto: "Art. 23-28", historial: [], adjuntos: [] },
  { id: 6, numero: "6", nombre: "Reglamento General de Elecciones", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "Propuestas de mejora: incorporar al art. 20 alternativas cuando no se presenten candidatos; eliminar art. 47 sobre consejeros de centro", enlace: "https://gestor.umag.cl/verificar/IenybNt1", decreto: "DEC N°007/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 7, numero: "7", nombre: "Reglamento de Secretaría General", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "Se debe presentar al CU del 28/08/2025", enlace: "https://gestor.umag.cl/storage/2025/2347/versiones/4/firmas/DEC-N28SU2025PDF-firmado-1.pdf", decreto: "DEC N°28/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 8, numero: "8", nombre: "Reglamento General de Facultades", articulo: "", estado: "En Revisión", progreso: 30, prioridad: "media", responsable: "VRAC", observaciones: "Revisar si se puede fusionar con el reglamento de estructuras", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 9, numero: "9", nombre: "Reglamento de Gestión, Evaluación y Aseguramiento de la Calidad", articulo: "Art. 53 letra a y b", estado: "En Revisión", progreso: 35, prioridad: "alta", responsable: "Dir. Aseguramiento de la Calidad", observaciones: "Art. 53 Estatutos letra a y b", enlace: "", decreto: "", articulo_estatuto: "Art. 53", historial: [], adjuntos: [] },
  { id: 10, numero: "10", nombre: "Reglamento de Estudios", articulo: "Art. 55", estado: "Pendiente", progreso: 10, prioridad: "alta", responsable: "VRAC", observaciones: "Art. 55 del estatuto. Revisar con Mario.", enlace: "", decreto: "", articulo_estatuto: "Art. 55", historial: [], adjuntos: [] },
  { id: 11, numero: "11", nombre: "Reglamento de Estructuras Académicas", articulo: "", estado: "En Revisión", progreso: 35, prioridad: "media", responsable: "VRAC / Dir. Docencia", observaciones: "Se presentó propuesta a VRAC, VRAF, SG y D. de Docencia. Coordinar reunión con decanos para revisión y posible unificación con reglamento general de facultades.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 12, numero: "12", nombre: "Reglamento del Comité de Aseguramiento de la Calidad", articulo: "", estado: "En Revisión", progreso: 30, prioridad: "media", responsable: "Dir. Aseguramiento de la Calidad", observaciones: "Fue remitido con observaciones a la Dirección de Aseguramiento de la Calidad", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 13, numero: "13", nombre: "Reglamento de Carrera Académica", articulo: "Art. 67", estado: "En Revisión", progreso: 25, prioridad: "alta", responsable: "Dir. Docencia", observaciones: "Art. 67. Se podría fusionar con jerarquía y carga, e incluso con el de Comisión de nombramiento y promoción académicos/as como títulos diferentes. Pablo Galaz debe recopilar reglamentos de otras universidades y generar listado de materias a regular. Reunión pendiente entre DJ, DD y Unidad de Gestión Docente.", enlace: "", decreto: "", articulo_estatuto: "Art. 67", historial: [], adjuntos: [] },
  { id: 14, numero: "14", nombre: "Reglamento de Asignación de Carga Académica", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Dir. Docencia", observaciones: "Propuesta de mejora: considerar en la carga administrativa a los coordinadores de campus", enlace: "https://gestor.umag.cl/verificar/hBeJOFkT", decreto: "DEC N°15/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 15, numero: "15", nombre: "Reglamento de Jerarquía Académica", articulo: "", estado: "En Revisión", progreso: 25, prioridad: "media", responsable: "Dir. Docencia", observaciones: "Dirección de Docencia propuso generar reunión entre DJ, DD y la Unidad de Gestión docente.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 16, numero: "16", nombre: "Reglamento de Promoción de un Académico", articulo: "Art. 68", estado: "En Proceso", progreso: 15, prioridad: "media", responsable: "Dir. Docencia", observaciones: "Art. 68. En redacción.", enlace: "", decreto: "", articulo_estatuto: "Art. 68", historial: [], adjuntos: [] },
  { id: 17, numero: "17", nombre: "Reglamento de Estímulos e Incentivos a Funcionarios de Apoyo", articulo: "Art. 71", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "VRAF", observaciones: "Art. 71. En estudio.", enlace: "", decreto: "", articulo_estatuto: "Art. 71", historial: [], adjuntos: [] },
  { id: 18, numero: "18", nombre: "Reglamento General de Estudiantes", articulo: "", estado: "En Proceso", progreso: 45, prioridad: "alta", responsable: "VRAE", observaciones: "Propuesta presentada al Consejo Universitario.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 19, numero: "19", nombre: "Reglamento para Uso de Bienes y Servicios de la Universidad", articulo: "Art. 78 letra f)", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "VRAF", observaciones: "Art. 78 letra f). En estudio.", enlace: "", decreto: "", articulo_estatuto: "Art. 78", historial: [], adjuntos: [] },
  { id: 20, numero: "20", nombre: "Reglamento de Procedimientos Disciplinarios de Estudiantes", articulo: "", estado: "Aprobado", progreso: 100, prioridad: "alta", responsable: "Secretaría General", observaciones: "El día 27 de agosto de 2025 se responden observaciones del Sr. Contralor. Observaciones de Dayana: https://docs.google.com/document/d/1D4iroX87I0FdohIUV-w7xOy5NF8cgWVr/edit", enlace: "https://gestor.umag.cl/storage/2025/538/versiones/3/firmas/DEC-N21SU2025PDF-firmado-1.pdf", decreto: "DEC N°21/SU/2025", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 21, numero: "21", nombre: "Reglamento del Consejo de Convivencia Universitaria", articulo: "Art. 81", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "Secretaría General", observaciones: "Art. 81. En estudio.", enlace: "", decreto: "", articulo_estatuto: "Art. 81", historial: [], adjuntos: [] },
  { id: 22, numero: "22", nombre: "Reglamento sobre Administración Financiera y Patrimonial", articulo: "Art. 86 letra g)", estado: "Pendiente", progreso: 5, prioridad: "alta", responsable: "VRAF", observaciones: "Art. 86 letra g). En estudio.", enlace: "", decreto: "", articulo_estatuto: "Art. 86", historial: [], adjuntos: [] },
  { id: 23, numero: "23", nombre: "Reglamento sobre Propiedad Intelectual", articulo: "Art. 90", estado: "Pendiente", progreso: 15, prioridad: "media", responsable: "VRI / Pedro Herrera", observaciones: "Pedro Herrera realizará ajuste normativo. Solicitud de presentación para CU de octubre 2025.", enlace: "https://drive.google.com/file/d/1C32f_54Amsw6CY9YGTIm3yYnvKftIEKy/view?usp=sharing", decreto: "DEC N°004/SU/2023", articulo_estatuto: "Art. 90", historial: [], adjuntos: [] },
  { id: 24, numero: "24", nombre: "Protocolo de Protección de Datos", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "media", responsable: "Secretaría General", observaciones: "En estudio.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 25, numero: "25", nombre: "Reglamento de Orden, Higiene y Seguridad", articulo: "", estado: "En Revisión", progreso: 30, prioridad: "media", responsable: "VRAF", observaciones: "", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 26, numero: "26", nombre: "Normativa del Mediador Universitario", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "baja", responsable: "Secretaría General", observaciones: "En estudio.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 27, numero: "27", nombre: "Normativa Relativa para la Emisión de Normas", articulo: "", estado: "Pendiente", progreso: 10, prioridad: "media", responsable: "Secretaría General", observaciones: "Se debe crear normativa que regule en qué caso debe emitirse una política, reglamento, instructivo, circular. Además podría incluirse materias relativas a decretos y resoluciones. Pasos: buscar normativa similar, establecer instrumentos que se regularán, determinar elementos mínimos que debe contener cada instrumento.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 28, numero: "28", nombre: "Reglamento de Tramitación de Convenios y Contratos", articulo: "", estado: "Pendiente", progreso: 10, prioridad: "media", responsable: "Secretaría General", observaciones: "Pasos: Crear Drive con material, reunir normativa similar, recabar opinión de Contraloría, reunión equipo jurídico, redacción de documento.", enlace: "", decreto: "Res. N°216/2019", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 29, numero: "29", nombre: "Normativa de Compatibilidad Estudios con Vida Familiar", articulo: "", estado: "Pendiente", progreso: 10, prioridad: "alta", responsable: "VRAE", observaciones: "Se debe redactar normativa de acuerdo al tenor de la Ley 21.790 sobre derechos de estudiantes cuidadores.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 30, numero: "30", nombre: "Reglamento de Incentivo al Retiro", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "baja", responsable: "VRAF", observaciones: "En estudio.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] },
  { id: 31, numero: "31", nombre: "Reglamento de Votaciones Bienestar", articulo: "", estado: "Pendiente", progreso: 5, prioridad: "baja", responsable: "VRAE / Bienestar", observaciones: "En estudio.", enlace: "", decreto: "", articulo_estatuto: "", historial: [], adjuntos: [] }
];

export const PLAZOS_DATA = [
  { id: 1, gestion: "Revisión de redacción", plazo: "90 días desde la propuesta", objeto: "Validar contenido normativo", formalidad: "Comisión de Redacción", requisito: "Propuesta inicial" },
  { id: 2, gestion: "Consulta a académicos", plazo: "60 días", objeto: "Incorporar feedback", formalidad: "Consulta pública", requisito: "Borrador disponible" },
  { id: 3, gestion: "Aprobación de Consejo", plazo: "45 días", objeto: "Aprobación final", formalidad: "Sesión del Consejo", requisito: "Informe favorable" },
  { id: 4, gestion: "Publicación oficial", plazo: "15 días", objeto: "Difusión general", formalidad: "Publicación web y gaceta", requisito: "Aprobación del Consejo" },
  { id: 5, gestion: "Implementación", plazo: "30 días", objeto: "Capacitación e inicio", formalidad: "Plan de implementación", requisito: "Publicación oficial" },
  { id: 6, gestion: "Seguimiento", plazo: "Permanente", objeto: "Monitoreo de cumplimiento", formalidad: "Reportes trimestrales", requisito: "Implementación activa" }
];
